buildscript = <<BUILDSCRIPT
    apt-get update
    apt-get install -y cmake make gcc automake libtool python-dev collectd-dev libsensors4-dev
    cd /vagrant
    make
BUILDSCRIPT

boxscript = <<BOXSCRIPT
    apt-get update
    apt-get install -y collectd-core
    cp -R /vagrant/_dist/* /
BOXSCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "builder" do |builder|
        builder.vm.box = "nntest_base"
        builder.vm.provision "shell", inline: buildscript
    end
    config.vm.define "boxer" do |boxer|
        boxer.vm.box = "nntest_base"
        boxer.vm.provision "shell", inline: boxscript
    end
end
